[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  node_version = "20.x"

[build.environment]
  SITE_NAME = "Neuro Swarm"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "src/server/functions"
