[toolchain]
anchor_version = "0.30.0"
[features]
seeds = false
skip-lint = false

[programs.localnet]
swarm_network = "FeDRrVnuisSuSPdUUuumZcpfLbXJK3QQkgkFaNR8qVgb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\neohe\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
